CREATE TABLE IF NOT EXISTS personal_contratos (
  id CHAR(36) NOT NULL,
  personal_id CHAR(36) NOT NULL,
  contrato_numero INT UNSIGNED NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  fecha_inicio DATE NULL,
  fecha_fin DATE NULL,
  motivo_cese TEXT NULL,
  activado_at TIMESTAMP NULL,
  activado_by_usuario_id CHAR(36) NULL,
  cerrado_at TIMESTAMP NULL,
  cerrado_by_usuario_id CHAR(36) NULL,
  origen_contrato_id CHAR(36) NULL,
  personal_ficha_id CHAR(36) NULL,
  snapshot_inicial_json JSON NULL,
  snapshot_json JSON NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_personal_contratos_numero (personal_id, contrato_numero),
  KEY idx_personal_contratos_estado (personal_id, estado),
  KEY idx_personal_contratos_fechas (fecha_inicio, fecha_fin),
  KEY fk_personal_contrato_activado_by (activado_by_usuario_id),
  KEY fk_personal_contrato_cerrado_by (cerrado_by_usuario_id),
  KEY fk_personal_contrato_origen (origen_contrato_id),
  KEY fk_personal_contrato_ficha (personal_ficha_id),
  CONSTRAINT fk_personal_contratos_personal FOREIGN KEY (personal_id) REFERENCES personal(id) ON DELETE CASCADE,
  CONSTRAINT fk_personal_contrato_activado_by FOREIGN KEY (activado_by_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_cerrado_by FOREIGN KEY (cerrado_by_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_origen FOREIGN KEY (origen_contrato_id) REFERENCES personal_contratos(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_ficha FOREIGN KEY (personal_ficha_id) REFERENCES personal_fichas(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
