CREATE TABLE IF NOT EXISTS personal_contratos (
  id CHAR(36) NOT NULL,
  personal_id CHAR(36) NOT NULL,
  contrato_numero INT UNSIGNED NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  origen_registro VARCHAR(30) NOT NULL DEFAULT 'NUEVO',
  es_historico TINYINT(1) NOT NULL DEFAULT 0,
  archivo_pendiente_regularizacion TINYINT(1) NOT NULL DEFAULT 0,
  observacion_historica TEXT NULL,
  tipo_contrato VARCHAR(40) NULL,
  puesto VARCHAR(191) NULL,
  area VARCHAR(191) NULL,
  mina VARCHAR(191) NULL,
  remuneracion VARCHAR(120) NULL,
  costo_hora VARCHAR(120) NULL,
  es_supervisor TINYINT(1) NULL,
  registrado_by_usuario_id CHAR(36) NULL,
  fecha_inicio DATE NULL,
  fecha_fin DATE NULL,
  motivo_cese TEXT NULL,
  activado_at TIMESTAMP NULL,
  activado_by_usuario_id CHAR(36) NULL,
  cerrado_at TIMESTAMP NULL,
  cerrado_by_usuario_id CHAR(36) NULL,
  signed_at TIMESTAMP NULL,
  signed_by_usuario_id CHAR(36) NULL,
  signed_contract_path VARCHAR(500) NULL,
  signed_contract_original_name VARCHAR(191) NULL,
  signed_contract_mime VARCHAR(120) NULL,
  signed_contract_size BIGINT UNSIGNED NULL,
  anulado_at TIMESTAMP NULL,
  anulado_by_usuario_id CHAR(36) NULL,
  motivo_anulacion TEXT NULL,
  origen_contrato_id CHAR(36) NULL,
  tipo_movimiento VARCHAR(40) NULL,
  observacion_renovacion TEXT NULL,
  estado_decision_renovacion VARCHAR(40) NULL,
  decision_final VARCHAR(40) NULL,
  motivo_no_renovacion VARCHAR(80) NULL,
  observacion_decision TEXT NULL,
  fecha_decision TIMESTAMP NULL,
  usuario_decision_id CHAR(36) NULL,
  fecha_cierre_no_renovacion TIMESTAMP NULL,
  usuario_cierre_no_renovacion_id CHAR(36) NULL,
  observacion_cierre_no_renovacion TEXT NULL,
  motivo_cese_controlado VARCHAR(80) NULL,
  observacion_cese_controlado TEXT NULL,
  fecha_cese_controlado DATE NULL,
  personal_ficha_id CHAR(36) NULL,
  snapshot_inicial_json JSON NULL,
  snapshot_json JSON NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_personal_contratos_numero (personal_id, contrato_numero),
  KEY idx_personal_contratos_estado (personal_id, estado),
  KEY idx_personal_contratos_fechas (fecha_inicio, fecha_fin),
  KEY fk_personal_contrato_registrado_by (registrado_by_usuario_id),
  KEY fk_personal_contrato_activado_by (activado_by_usuario_id),
  KEY fk_personal_contrato_cerrado_by (cerrado_by_usuario_id),
  KEY fk_personal_contrato_signed_by (signed_by_usuario_id),
  KEY fk_personal_contrato_anulado_by (anulado_by_usuario_id),
  KEY fk_personal_contrato_origen (origen_contrato_id),
  KEY fk_personal_contrato_decision_by (usuario_decision_id),
  KEY fk_personal_contrato_cierre_no_renovacion_by (usuario_cierre_no_renovacion_id),
  KEY fk_personal_contrato_ficha (personal_ficha_id),
  CONSTRAINT fk_personal_contratos_personal FOREIGN KEY (personal_id) REFERENCES personal(id) ON DELETE CASCADE,
  CONSTRAINT fk_personal_contrato_registrado_by FOREIGN KEY (registrado_by_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_activado_by FOREIGN KEY (activado_by_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_cerrado_by FOREIGN KEY (cerrado_by_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_signed_by FOREIGN KEY (signed_by_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_anulado_by FOREIGN KEY (anulado_by_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_origen FOREIGN KEY (origen_contrato_id) REFERENCES personal_contratos(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_decision_by FOREIGN KEY (usuario_decision_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_cierre_no_renovacion_by FOREIGN KEY (usuario_cierre_no_renovacion_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_personal_contrato_ficha FOREIGN KEY (personal_ficha_id) REFERENCES personal_fichas(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
