ALTER TABLE asistencia_detalle
  ADD COLUMN IF NOT EXISTS grupo_trabajo_detalle_id CHAR(36) NULL AFTER asistencia_id,
  ADD COLUMN IF NOT EXISTS rq_proserge_detalle_id CHAR(36) NULL AFTER grupo_trabajo_detalle_id,
  ADD COLUMN IF NOT EXISTS puesto_snapshot VARCHAR(191) NULL AFTER trabajador_id,
  ADD COLUMN IF NOT EXISTS posicion_asignacion_snapshot VARCHAR(20) NULL AFTER puesto_snapshot,
  ADD COLUMN IF NOT EXISTS tipo_asignacion_snapshot VARCHAR(20) NULL AFTER posicion_asignacion_snapshot,
  ADD COLUMN IF NOT EXISTS estado_distribucion_snapshot VARCHAR(20) NULL AFTER tipo_asignacion_snapshot,
  ADD COLUMN IF NOT EXISTS motivo_estado TEXT NULL AFTER estado,
  ADD COLUMN IF NOT EXISTS origen_registro VARCHAR(20) NULL AFTER motivo_estado,
  ADD COLUMN IF NOT EXISTS marcado_por_id CHAR(36) NULL AFTER observaciones,
  ADD COLUMN IF NOT EXISTS marcado_at TIMESTAMP NULL AFTER marcado_por_id,
  ADD COLUMN IF NOT EXISTS updated_by CHAR(36) NULL AFTER marcado_at,
  ADD KEY IF NOT EXISTS idx_asistencia_detalle_gtd (grupo_trabajo_detalle_id),
  ADD KEY IF NOT EXISTS idx_asistencia_detalle_rqpd (rq_proserge_detalle_id),
  ADD KEY IF NOT EXISTS idx_asistencia_detalle_trabajador (trabajador_id),
  ADD KEY IF NOT EXISTS idx_asistencia_detalle_estado (estado),
  ADD KEY IF NOT EXISTS idx_asistencia_detalle_marcado_at (marcado_at),
  ADD UNIQUE KEY IF NOT EXISTS uq_asistencia_detalle_gtd (asistencia_id, grupo_trabajo_detalle_id);

CREATE TABLE IF NOT EXISTS grupo_trabajo_detalle_actividades (
  id CHAR(36) NOT NULL,
  grupo_trabajo_detalle_id CHAR(36) NOT NULL,
  rq_mina_actividad_id CHAR(36) NOT NULL,
  es_principal TINYINT(1) NOT NULL DEFAULT 1,
  observacion TEXT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gtd_actividad (grupo_trabajo_detalle_id, rq_mina_actividad_id),
  UNIQUE KEY uq_gtd_actividad_principal (grupo_trabajo_detalle_id, es_principal),
  KEY idx_gtd_actividades_actividad (rq_mina_actividad_id),
  CONSTRAINT fk_gtd_actividades_detalle FOREIGN KEY (grupo_trabajo_detalle_id) REFERENCES grupo_trabajo_detalle(id) ON DELETE CASCADE,
  CONSTRAINT fk_gtd_actividades_actividad FOREIGN KEY (rq_mina_actividad_id) REFERENCES rq_mina_actividades(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS parada_ejecucion_resumen (
  id CHAR(36) NOT NULL,
  rq_mina_id CHAR(36) NOT NULL,
  rq_mina_plan_id CHAR(36) NULL,
  rq_mina_actividad_grupo_id CHAR(36) NULL,
  rq_mina_actividad_id CHAR(36) NULL,
  actividad_key VARCHAR(50) NOT NULL DEFAULT '__GRUPO__',
  fecha DATE NOT NULL,
  turno VARCHAR(20) NOT NULL,
  planificado INT NOT NULL DEFAULT 0,
  programado INT NOT NULL DEFAULT 0,
  presentes INT NOT NULL DEFAULT 0,
  tardanzas INT NOT NULL DEFAULT 0,
  ausentes INT NOT NULL DEFAULT 0,
  justificados INT NOT NULL DEFAULT 0,
  no_corresponde INT NOT NULL DEFAULT 0,
  pendientes_marcacion INT NOT NULL DEFAULT 0,
  titulares_presentes INT NOT NULL DEFAULT 0,
  suplentes_presentes INT NOT NULL DEFAULT 0,
  adicionales_presentes INT NOT NULL DEFAULT 0,
  sin_clasificar_presentes INT NOT NULL DEFAULT 0,
  personal_sin_actividad INT NOT NULL DEFAULT 0,
  brecha_plan_programado INT NOT NULL DEFAULT 0,
  brecha_programado_real INT NOT NULL DEFAULT 0,
  brecha_plan_real INT NOT NULL DEFAULT 0,
  exceso_programado INT NOT NULL DEFAULT 0,
  exceso_real INT NOT NULL DEFAULT 0,
  porcentaje_programacion DECIMAL(8,2) NOT NULL DEFAULT 0,
  porcentaje_asistencia DECIMAL(8,2) NOT NULL DEFAULT 0,
  porcentaje_cumplimiento_real DECIMAL(8,2) NOT NULL DEFAULT 0,
  asistencia_cerrada TINYINT(1) NOT NULL DEFAULT 0,
  datos_completos TINYINT(1) NOT NULL DEFAULT 0,
  source_closed_at TIMESTAMP NULL,
  recalculated_at TIMESTAMP NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_parada_ejecucion_scope (rq_mina_plan_id, rq_mina_actividad_grupo_id, actividad_key, fecha, turno),
  KEY idx_parada_ejecucion_rq_fecha_turno (rq_mina_id, fecha, turno),
  KEY idx_parada_ejecucion_actividad (rq_mina_actividad_id),
  CONSTRAINT fk_parada_ejecucion_rq FOREIGN KEY (rq_mina_id) REFERENCES rq_mina(id) ON DELETE CASCADE,
  CONSTRAINT fk_parada_ejecucion_plan FOREIGN KEY (rq_mina_plan_id) REFERENCES rq_mina_planes(id) ON DELETE SET NULL,
  CONSTRAINT fk_parada_ejecucion_grupo FOREIGN KEY (rq_mina_actividad_grupo_id) REFERENCES rq_mina_actividad_grupos(id) ON DELETE SET NULL,
  CONSTRAINT fk_parada_ejecucion_actividad FOREIGN KEY (rq_mina_actividad_id) REFERENCES rq_mina_actividades(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
